### ISSUE TITLE
Resizable drawer issue after scrolling

### ISSUE THREAD

**Issue by weilinzung** [s-r-x/bull-monitor#13]
Hi, @saade @s-r-x  please check the below recording, I can't resize the drawer after scrolling.

- Chrome:  91.0.4472.77 (Official Build) (x86_64)
- macOS Big Sur
- "@bull-monitor/express": "^0.26.0"

https://user-images.githubusercontent.com/7368063/121697771-5f260180-ca9b-11eb-89f2-731a02c845aa.mp4

---

Aslo, do you think it is possible to allow resizable width until to `50vw`?
<img width="930" alt="Screen Shot 2021-06-11 at 9 54 03 AM" src="https://user-images.githubusercontent.com/7368063/121697793-65b47900-ca9b-11eb-9c1e-ec44f99fd6e0.png">

**Comment by saade** [comment]
Hmm, i can hotfix that. No problem

@s-r-x what you think about the 50vw? Currently it allows up to 2x drawerWidth

**Comment by s-r-x** [comment]
@saade sure, why not

**Comment by saade** [comment]
np, just to be inline with you =)

ps. this is in a FHD monitor, looks kinda a overkill

![image](https://user-images.githubusercontent.com/14329460/121720497-90152f00-cab9-11eb-888d-24adbb3500ab.png)

**Comment by weilinzung** [comment]
what about 30vw? or max to 5x width? it is good to see these as screenshots.

**Comment by s-r-x** [comment]
@saade, yeah,  looks weird. reminds me of Insomnia's ui. but if the man likes queue names like test2_test2_test2_extension_dissaproval - let him have it!

**Comment by s-r-x** [comment]
actually right now I'm not quite sure that resizable drawer was a good idea. maybe simple material tooltips would be a better option... Personally I'll be happy with any option, because standard drawer width covers all my needs :)

**Comment by s-r-x** [comment]
@weilinzung fixed in 0.27.2
