### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by melalj** [s-r-x/bull-monitor#15]
Is there any documentation regarding how to use:
 - the graphql playground (with some examples?)
 - the data search key/value?

**Comment by s-r-x** [comment]
for graphql api you can check the schema. i guess it's pretty straightforward with arguments and all that stuff. if you have any questions about specific queries/mutations - you can ask here.
data search is simple as that. key can by any value supported by lodash.get. for example if your data is {"user": {"id": 1}} and you want to find a user with id 1  search key will be "user.id" and term 1. in the future i want to combine key and term into one field and use jsonpath syntax to allow search by multiple fields.
