### ISSUE TITLE
Graph shows no data and "Invalid Date" error

### ISSUE THREAD

**Issue by kamal0808** [s-r-x/bull-monitor#18]
Is there some way to fix the Invalid Date error shown at bottom right?

![Screenshot 2021-07-15 at 9 20 12 PM](https://user-images.githubusercontent.com/15616412/125818134-87859379-c5b8-4014-a37a-70771271af55.png)

**Comment by s-r-x** [comment]
@kamal0808 sure. you see that weirdness only when there are no metrics yet or queue is blacklisted. i guess some little placeholder will do the trick

**Comment by s-r-x** [comment]
@kamal0808 fixed in 0.28.1
