### ISSUE TITLE
[UI] Queue prefix

### ISSUE THREAD

**Issue by saade** [s-r-x/bull-monitor#19]
I think it should be really nice and useful to show the queue prefix on the sidebar.

I have a multi-tenant app, and each tenant is using a different prefix to identify it. I don't have any visual separation between them.

## Suggestion A
![image](https://user-images.githubusercontent.com/14329460/126374748-c4db7af5-7248-41b4-92bc-a96737b5bfaf.png)

## Suggestion B (i think its better)
![image](https://user-images.githubusercontent.com/14329460/126375179-0d04bde6-4c04-4e96-87d5-a0c2e3215a57.png)

**Comment by s-r-x** [comment]
@saade i think the overall idea is nice, but i'm not quite sure how to implement it properly. You use colons to separate the queue name from it's namespace, i personally prefer to use double colons, some other people like commas, dots, etc. One option is to add namespace(or prefix -  as you call it) separator input somewhere in the ui options...

**Comment by s-r-x** [comment]
btw i'm not quite sure what you did on the first screen.i don't see any difference between this and the current ui

**Comment by saade** [comment]
Bull have the option to configure `prefix` for each queue created. The default is "bull".

So internally, bull puts all queue data inside a "db" called bull. So naturally it have a prefix, but this is customizable.

My sugestion is just to print this prefix somewhere on the screen. This property is on the queue object itself.

**Comment by saade** [comment]
My queue name is "jobs" not "tenant1:jobs".

"jobs" is the queue name, and "tenant1" is the bull queue prefix that i configured for that queue. (prefix defaults for "bull" when not provided)

**Comment by s-r-x** [comment]
@saade understood. it should be pretty simple then

**Comment by saade** [comment]
Ya! I suggest the second option (list headers).

Giving 3 queues for 3 different tenants:

tenant1:Queue A
tenant1:Queue B
tenant1:Queue C
tenant2:Queue A
tenant2:Queue B
tenant2:Queue C
tenant3:Queue A
tenant3:Queue B
tenant3:Queue C


I personally prefer:

Tenant 1
----------------
Queue A
Queue B
Queue C

Tenant 2
----------------
Queue A
Queue B
Queue C

Tenant 3
----------------
Queue A
Queue B
Queue C

**Comment by s-r-x** [comment]
@saade added in 0.29.0.  There is a new checkbox in the settings modal called "Group queues by prefix".

**Comment by saade** [comment]
Sweet!! Thank you, gonna test it tomorrow

**Comment by saade** [comment]
Hey!, Found a bug using this new implementation.

In the example, i have two queues with the same name, but with different prefixes, the bug is shown below.

![jobs](https://user-images.githubusercontent.com/14329460/127034763-40bc1a65-2ed8-4a4b-9f3e-04574cea49cb.gif)

The two queues are "linked", and jobs listing too

**Comment by s-r-x** [comment]
I convert the queues from array to map(for performance reasons) at the backend, so names should be unique. I actually never thought that queue names could be the same. You can create a pr for this use case if you want to, because this task is not my top priority at the moment.

**Comment by s-r-x** [comment]
Also right now name is the only available identifier for queue, so non unique queue names will break litetally everything

**Comment by saade** [comment]
Understood, yeah, queues can have the same name if prefix is diferent, i'll look at that in my spare time :)

**Comment by saade** [comment]
Understood, yeah, queues can have the same name if prefix is diferent, i'll look at that in my spare time :)

![image](https://user-images.githubusercontent.com/14329460/127039791-86c3d13b-f713-424e-acda-9a656de8c908.png)

**Comment by s-r-x** [comment]
One way to do it is to add an id field to the every queue. It can be concatenated name and prefix then converted to base64. Still hell of a refactor because all mutations and queries is treating queue name as it's id

**Comment by s-r-x** [comment]
@saade released in v1.0.0
