### ISSUE TITLE
Retry multiple failed jobs feature

### ISSUE THREAD

**Issue by weilinzung** [s-r-x/bull-monitor#2]
Hi,

Can this have a retry multiple failed jobs feature?
I think the table should be easy to migrate with checkbox: https://material-ui.com/components/tables/#data-table

Thanks!

**Comment by s-r-x** [comment]
> Hi,
> 
> Can this have a retry multiple failed jobs feature?
> I think the table should be easy to migrate with checkbox: https://material-ui.com/components/tables/#data-table
> 
> Thanks!

hello. thanks for the issue. i'll check that out

**Comment by weilinzung** [comment]
@s-r-x Also, maybe another request, would be nice to be able to download multiple jobs as JSON file.

**Comment by s-r-x** [comment]
> Hi,
> 
> Can this have a retry multiple failed jobs feature?
> I think the table should be easy to migrate with checkbox: https://material-ui.com/components/tables/#data-table
> 
> Thanks!

added in 0.14.0!

for this json thing please open up a separate issue if you're still interested in it
