### ISSUE TITLE
feat: Add a bigger (perhaps customized) value to 'per page'

### ISSUE THREAD

**Issue by saade** [s-r-x/bull-monitor#20]
I have a lot of jobs inside a queue, and sometimes i need to investigate an error or retry more than 75 itens.

My suggestion is to add a bigger value (like mysql uses 500), or a input field to enter a custom amount of itens per page

![image](https://user-images.githubusercontent.com/14329460/129731442-c0dd466c-54cf-4fba-90e2-854c79733543.png)

**Comment by s-r-x** [comment]
@saade i added more "per page" options(up to 500) in 1.2.0. performance will be poor though
