### ISSUE TITLE
Status chips are transparent inside tables

### ISSUE THREAD

**Issue by saade** [s-r-x/bull-monitor#22]
#21 caused status chips inside tables to be transparent too.

I think #21 should only affect the sidebar chips, not all chips

![image](https://user-images.githubusercontent.com/14329460/131261629-e975cc9b-3f45-4b9f-a789-6f49ded3add6.png)

![image](https://user-images.githubusercontent.com/14329460/131261645-392143ca-27ff-4d7b-b5bf-39b3ffe88763.png)

**Comment by s-r-x** [comment]
oh, i missed this one. thanks

**Comment by s-r-x** [comment]
@s-r-x fixed in 1.31.0
