### ISSUE TITLE
[NEW FEATURE] Login Page

### ISSUE THREAD

**Issue by MarconWillian** [s-r-x/bull-monitor#23]
Hey guys, how are you doing? Are you planning to implement a login page? I'd love to protect my project  with a login page.
If you don't, I'm thinking to create a pull request with this feature.

**Comment by s-r-x** [comment]
@MarconWillian hello. If a simple basic auth strategy covers your needs, you can check the examples folder - there are some examples for all supported frameworks. If you need more advanced auth that includes session/bearer token/whatever - you should implement it in your own code.

some abstract example for express
```typescript
@MarconWillian hello. If a simple basic auth strategy covers your needs, you can check the examples folder - there are some examples for all supported frameworks. If you need more advanced auth that includes session/bearer token/whatever - you should implement it in your own code.

some abstract example for express
```typescript
import { BullMonitorExpress } from '@bull-monitor/express';
import express, { Request, Response, NextFunction } from 'express';

const app = express();
const monitor = new BullMonitorExpress({
  queues: [],
});
const authGuard = (req: Request, res: Response, next: NextFunction) => {
  if (req.session?.role !== 'REQUIRED_ROLE') {
    res.redirect('/login');
  } else {
    next();
  }
};
monitor.init().then(() => {
  app.use('/', authGuard, monitor.router);
});
app.listen(3000);
```

**Comment by samuelpares** [comment]
Hey @s-r-x, could you provide basic auth example for nestjs?
