### ISSUE TITLE
Data search term should be exact equal to data search key

### ISSUE THREAD

**Issue by saade** [s-r-x/bull-monitor#24]
Currently, data search term input performs a "like" query inside the object values,  when it should be exact equal IMHO

example:

If i type: `Product` onto the term, it matches items with term `ProductOption` when it should only match `Product` (exact equal ===).

My sugestion is to add "like wildcards" support to this field, so it will become:

`Product` === `Product`
`Product%` === `ProductOption`
`%ProductOption%` === `AProductOption`

`Jhon` === `Jhon`
`Jhon%` === `Jhon Doe`
`%Jhon%` === `Marcus Jhon Doe`

![image](https://user-images.githubusercontent.com/14329460/131935468-58a76c6e-77d6-456d-8138-ef738505ed3a.png)

**Comment by s-r-x** [comment]
@saade actually i was thinking about adding support for more advanced data queries.
here are some json query libraries that i'm now playing with:

- [json-query](https://github.com/auditassistant/json-query)
- [alasql](https://github.com/agershun/alasql)
- [jsonpath-plus](https://github.com/JSONPath-Plus/JSONPath)

**Comment by saade** [comment]
Sweet! json-query looks promising,

**Comment by saade** [comment]
Sweet!

json-query looks promissing for daily-use/monitoring

alasql opens so much possibilities for advanced queries, thats nice, but maybe bull-monitor should render data in a table to give a more "database feeling" and a better viewing of the data

**Comment by s-r-x** [comment]
@saade added in 2.0.1
