### ISSUE TITLE
How to pass bull queue instance to BullMonitorExpress once the BullMonitorExpress instantiate

### ISSUE THREAD

**Issue by nareshkharola123** [s-r-x/bull-monitor#28]
I'm trying to integrate [@bull-monitor/express
](https://www.npmjs.com/package/@bull-monitor/express) in in loopback4. I somehow integrate the Bull-monitor-express in loopback4. below is an example that I have followed. 

import { BullMonitorExpress } from '@bull-monitor/express';
import Express from 'express';

const port = 3000;
const baseUrl = '/some/nested/url';
(async () => {
  const app = Express();
  const monitor = new BullMonitorExpress({ queues: [] });
  await monitor.init();
  app.use(baseUrl, monitor.router);
  app.listen(port, () => console.log(`http://localhost:${port}${baseUrl}`));
})();

if I pass queues while `new BullMonitorExpress({ queues})` is instantiating its perfectly working fine. but I'm not able to pass queues  post instantiation of `new BullMonitorExpress({ queues: []})` .
I'm not able to find any thing regarding this in the document. can somebody help me with this?

**Comment by s-r-x** [comment]
@nareshkharola123 hello, i'll look into it

**Comment by s-r-x** [comment]
@nareshkharola123 since version **2.6.0** you can do this:

```typescript
import { BullMonitorExpress } from '@bull-monitor/express';
import Express from 'express';
import Queue from 'bull';

(async () => {
  const app = Express();
  const monitor = new BullMonitorExpress({ queues: [] });
  await monitor.init();
  app.use('/', monitor.router);
  app.listen(3000);
  
  // here
  monitor.queues = [new Queue('1')];
})();
```

does it cover your needs?

**Comment by nareshkharola123** [comment]
@s-r-x 
I try your solution its working.., but when I'm adding new queue for example `new Queue('test-two')`. its not displaying in bull-monitor.
Here is example:

import { BullMonitorExpress } from '@bull-monitor/express';
import Express from 'express';
import Queue from 'bull';

(async () => {
  const app = Express();
  const monitor = new BullMonitorExpress({ queues: [] });
  await monitor.init();
  app.use('/', monitor.router);
  app.listen(3000);
  
  // here
  let myQueues = [new Queue('test-one')];
  monitor.queues = myQueues
  
  setInterval(()=> {
     myQueues.push(new Queue('test-two'))
  }, 1000)
})();

**Comment by s-r-x** [comment]
@nareshkharola123, to update the queues you should always use "monitor.queues = [your queues]"
monitor.queues is just a [setter](https://github.com/s-r-x/bull-monitor/blob/main/packages/root/src/index.ts#L33) for internal _queues property. your queues is a simple array, so bull-monitor doesn't know about was it updated or not. in other words, it's immutable from a library perspective.

```typescript
let myQueues = [new Queue('test-one')];
monitor.queues = myQueues

// this one won't work
myQueues.push(new Queue('test-two'))

// this one will work
monitor.queues = [...myQueues, new Queue('test-two')];
// and this one too
myQueues.push(new Queue('test-two'))
monitor.queues = myQueues;
```
