### ISSUE TITLE
FR: a better way to search job instead of job id

### ISSUE THREAD

**Issue by weilinzung** [s-r-x/bull-monitor#4]
Hi, is possible to have an advanced job search?

Currently, job id search is not that useful for us because of the number of the same jobs that run on the same day or time.

To give you an example how our list looks like:
<img width="1441" alt="Screen Shot 2021-05-19 at 8 47 39 AM" src="https://user-images.githubusercontent.com/7368063/118815186-f8883c00-b87e-11eb-9d28-7388da11d0e5.png">

How about being able to deep search inside of each job? like we can search job data's key value? Thanks!

<img width="1450" alt="Screen Shot 2021-05-19 at 8 49 31 AM" src="https://user-images.githubusercontent.com/7368063/118815710-777d7480-b87f-11eb-9308-3d96af0293c9.png">
<img width="1452" alt="Screen Shot 2021-05-19 at 8 50 08 AM" src="https://user-images.githubusercontent.com/7368063/118815714-777d7480-b87f-11eb-82ab-9efea2fa7427.png">

**Comment by s-r-x** [comment]
that's a tough one actually. bull doesn't have such things built-in. with a little help of lua it's possible, i guess. but now we're working only with javascript interface that bull provides to us. and dealing with redis directly doesn't look like fun to me.

**Comment by s-r-x** [comment]
got some ideas how it can be done, though. I'll try to ship it next week

**Comment by ccollie** [comment]
> got some ideas how it can be done, though. I'll try to ship it next week

I'm really interested in this. I have a complex solution that does an `infix` to `postfix` conversion on a  filter expression, and implements filtering (including expressions) using an `rpn` evaluator in `lua`.  It allows filters like:

```javascript
job.data.accountId == "12345" && job.name.startsWith("purchase") && job.data.amount > 2000
```
It uses `scan` to be more efficient, and pageable cursor is managed from the `node` end of things.

Previously I had a `mongo` compatible evaluator in `lua` which worked, but was too complex for my liking.

**Comment by s-r-x** [comment]
don't want to upset you, but i'm not going to implement such complex queries(at least for now).  i was thinking about more simple one line lodash.get like notation. user.id, payload.some.key and so on(one field per query). it uses scan too((i'm going to expose a scan count parameter in config) and pipeline from ioredis. text search is done in good ol' javascript. no lua, nothing fancy. but still works reasonably fast, at least at my modest scale. btw if you want to turn this ui into elastic or something - that would be awesome, prs are always welcome!

**Comment by ccollie** [comment]
> but i'm not going to implement such complex queries(at least for now)
I completely understand. I implemented this for my own purposes ( a more full-featured monitor, including metrics and alerts)
The code is already written, it just needs more testing.

Im interested because I always get inspiration from alternate implementations.

**Comment by s-r-x** [comment]
https://github.com/ccollie/toro-api - is that it? looks solid! metrics is sounds like a pretty cool feature actually. I would love to have that too. I guess that would be a next milestone.

**Comment by ccollie** [comment]
Yup thats me.  It's definitely alpha level, but I'm working to get it into presentable shape.

**Comment by ccollie** [comment]
BTW - the old `mongo` compatible implementation is here

https://github.com/ccollie/toro-api/blob/master/src/server/commands/getJobsByFilter-1.lua

The newer one is here:
https://github.com/ccollie/toro-api/blob/filter-fixes/src/server/commands/filterJobs-1.lua

The driver is here
https://github.com/ccollie/toro-api/blob/3f7a05d0f5958c106f1916768f9cd123de215243/src/server/queues/job-filters.ts#L217

Tests (some failing)
https://github.com/ccollie/toro-api/blob/filter-fixes/__tests__/server/commands/filterJobs.spec.ts

**Comment by s-r-x** [comment]
impressive. helluva search engine you got here. but wouldn't it be easier to just drop bull and use agenda to have all that mongo search fanciness?😎

**Comment by ccollie** [comment]
> impressive. helluva search engine you got here. but wouldn't it be easier to just drop bull and use agenda to have all that mongo search fanciness?😎

Sure, but i'm building this specifically for `bull` :-)

**Comment by s-r-x** [comment]
added in 0.21.0

**Comment by weilinzung** [comment]
@s-r-x not sure if i am using it properly? <img width="993" alt="Screen Shot 2021-05-26 at 9 59 17 AM" src="https://user-images.githubusercontent.com/7368063/119673026-0d2d7c80-be09-11eb-90c0-515eb1629c61.png">

**Comment by s-r-x** [comment]
this is a demo. you can create PR with mock for it if you want to.

**Comment by weilinzung** [comment]
@s-r-x cool. thanks!

**Comment by s-r-x** [comment]
@weilinzung for your data the key will be, for example, payload.customerId or payload.dateRange.startDate. query for multiple fields is not supported yet, but I think it's quite possible in the future. I just need to come up with syntax and some other fun stuff

**Comment by weilinzung** [comment]
@s-r-x I think one key so far is good for us. thanks!!!
