### ISSUE TITLE
Error when gettings failed jobs

### ISSUE THREAD

**Issue by carlgrundberg** [s-r-x/bull-monitor#48]
Sometimes we have a few failed jobs but when trying to list them in bull-monitor we get this message.

![image](https://user-images.githubusercontent.com/928407/150488876-143a5f77-421e-4bac-81a6-f0de86a65e47.png)

Javascript console shows this.

![image](https://user-images.githubusercontent.com/928407/150488931-2b5671a8-6dd4-4d76-80d2-34bf8bc5e23f.png)

**Comment by s-r-x** [comment]
@carlgrundberg hello, are you using bull or bullmq?

**Comment by carlgrundberg** [comment]
Bull

**Comment by s-r-x** [comment]
[this one](https://github.com/OptimalBits/bull/pull/159#issue-103502871) is related, i believe. nan timestamp is really weird

**Comment by s-r-x** [comment]
@carlgrundberg fixed in 3.3.1

**Comment by carlgrundberg** [comment]
Thanks!
