### ISSUE TITLE
Queue list name truncated

### ISSUE THREAD

**Issue by weilinzung** [s-r-x/bull-monitor#5]
<img width="793" alt="Screen Shot 2021-06-01 at 7 32 32 AM" src="https://user-images.githubusercontent.com/7368063/120316614-9d593f00-c2ab-11eb-9b5d-bea721039293.png">

The queue name is truncated because of the sidebar width. Maybe add the queue name on the right side as the title? or overflow on the `MuiListItemText-root` instead, so still be able to scroll on the text? and also add `<title>` Tag to each queue?

Thanks.

**Comment by s-r-x** [comment]
x overflow inside drawer - definitely no. "Maybe add the queue name on the right side as the title" - this one is better, in my opinion. title tag would be a nice addition too. we can incapsulate the title logic inside some hook and replace one on active queue change event in useeffect or something. or just use helmet. would you like to create a pr? this task should be pretty easy.

**Comment by s-r-x** [comment]
actually there is another option - make drawer resizable. it'll be a little bit tougher to implement, due to the material-ui internals(especially on mobile devices), but it would be awesome to have this feature!

**Comment by saade** [comment]
Hey @weilinzung and @s-r-x , take a look at this: #7

**Comment by s-r-x** [comment]
@weilinzung resizable drawer was added in version 0.22.0(thanks to @saade). does it cover your needs?

**Comment by weilinzung** [comment]
@s-r-x @saade yeah and thanks!!!
