### ISSUE TITLE
Express 5 Support?

### ISSUE THREAD

**Issue by robincsamuel** [s-r-x/bull-monitor#50]
I've been using the bull monitor with express `4.x` and am upgrading my project to express `5.x`. However, bull monitor stopped working after upgrading the express version. The dashboard loads fine but the graphql requests are stuck at `pending` status.

Any idea?

<img width="1920" alt="Screenshot 2022-02-28 at 4 57 19 PM" src="https://user-images.githubusercontent.com/4545992/155975848-d18b6932-422e-436f-9129-5ea3b4087b74.png">
,

**Comment by s-r-x** [comment]
@robincsamuel hello, looks like apollo-server-express doesn't support express 5 (and it's still in alpha btw) so i'm closing this for now

**Comment by robincsamuel** [comment]
It's currently in beta, fyi :)

**Comment by robincsamuel** [comment]
I tried to debug the issue and figured out the root cause. It works fine if I pass `bodyParserConfig: false` to the `applyMiddleware` method ([source](https://github.com/s-r-x/bull-monitor/blob/main/packages/express/src/index.ts#L15)). However, I don't see a way to pass this config via bull monitor.

@s-r-x Any idea?

**Comment by robincsamuel** [comment]
Adding a middleware like this fixes the issue since body-parser checks for req._body to see if it's already parsed and skips parsing in that case.

```js
router.post('/queues/graphql', (req, res, next) => {
      req['_body'] = true;
      return next();
});
```

I think it'd be great if we can pass the Apollo Server/applyMiddleware options via bull monitor configuration. I'd be happy to raise a PR if you think that's a good idea :)

**Comment by s-r-x** [comment]
@robincsamuel n1. I think we can add some config to the init method with something like useExpress5: boolean, and tweak bodyparserconfig based on that. wdyt?

**Comment by s-r-x** [comment]
I don't want to let the library users to deal with any internal dependency (like apollo server) directly, so let's stick with some abstraction for now

**Comment by robincsamuel** [comment]
Okay, that makes sense. What about passing a more generic option like `disableBodyParser` and `disableCors`? I think a flag based on the express version may become irrelevant in the future or will end up adding more flags.

Or maybe, we can detect the express version and handle this without a flag.

**Comment by s-r-x** [comment]
sounds good

**Comment by s-r-x** [comment]
both are fine, do whatever you think fits the best
