### ISSUE TITLE
User authentication needed to access UI page

### ISSUE THREAD

**Issue by frankgo81** [s-r-x/bull-monitor#57]
Curently it seems that any one can access the bull-monitor page, how to protect the page with password or jwt token?

- Nestjs
import { BullModule } from '@nestjs/bull';
import { MiddlewareConsumer, Module, NestModule } from '@nestjs/common';
import { BullMonitorService } from './bull-monitor.service';
import { Q_AUDIO_NAME } from '../audio-queue/audio.interface';

@Module({
  imports: [BullModule.registerQueue({ name: Q_AUDIO_NAME })],
  providers: [BullMonitorService],
})
export class BullMonitorModule implements NestModule {
  constructor(private monitor: BullMonitorService) {}
  async configure(consumer: MiddlewareConsumer) {
    await this.monitor.init();
    consumer.apply(this.monitor.router).forRoutes('/bull-monitor');
  }
}

**Comment by s-r-x** [comment]
@frankgo81, https://github.com/s-r-x/bull-monitor/issues/23
