### ISSUE TITLE
Redis ACL

### ISSUE THREAD

**Issue by autarchprinceps** [s-r-x/bull-monitor#58]
The version of ioredis used, doesn't work with Redis ACLs, as it doesn't pass a user to AUTH.
I tested the old version you use, and get the following error, but with e.g. 5.0.5 and the same URL it works completely.

> [ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled.
    at parseError (/root/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/root/node_modules/redis-parser/lib/parser.js:302:14)

**Comment by s-r-x** [comment]
@autarchprinceps, what do you mean by that? ioredis is not even in the list of the dependencies...
