### ISSUE TITLE
Repeatable jobs do not work properly

### ISSUE THREAD

**Issue by rdu** [s-r-x/bull-monitor#61]
Repeatable jobs could not be added correctly via "Add Job".

The job is placed in the "delayed" state and is also executed at the specified time, but never again afterwards. If I create the job directly via the Bull library with the exact same parameters, it remains in the "delayed" state until (if) an end condition occurs.

My concrete example (without end condition):

**Job**
`
{
  "payload": ...
}
`
**Options**
`
{
    "repeat": {
      "every": 60000
    }
  }
`

The job is even given an ID that indicates that it is a "repeatable job", but it is not executed again.

![Bildschirmfoto von 2022-08-22 10-13-14](https://user-images.githubusercontent.com/445462/185872784-b5a6b72b-bdd0-4bba-a5a2-104c9a156d9d.png)

**Comment by s-r-x** [comment]
![Снимок](https://user-images.githubusercontent.com/41614937/211523003-988caa57-40ff-45bd-b5cc-072ee321a5a3.PNG)
![Снимок2](https://user-images.githubusercontent.com/41614937/211523013-07bf90b1-b9b4-4627-80bf-fd735b17d75c.PNG)

i just copypasted your job config and it looks like everything works as expected. fyi there is no magic under the hood: bull-monitor just passes your job config directly to bull or bullmq  without any preprocessing (except, of course, json parsing)
