### ISSUE TITLE
Apollo cache configuration

### ISSUE THREAD

**Issue by amydinsyahira** [s-r-x/bull-monitor#62]
Hi @s-r-x, 

I got the error `Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set cache: "bounded" or persistedQueries: false in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.` when running with `production` environment.

Is there any way to set `cache: "bounded"` or `persistedQueries: false` in Bull Monitor config?
or perhaps config to set cache with ioredis?

**Comment by matteratomic** [comment]
Also discovered this issue

**Comment by itshig** [comment]
Any resolution?  I'm receiving the error as well. 

`Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set cache: "bounded" or persistedQueries: false in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.`

**Comment by s-r-x** [comment]
fixed in **5.0.3**
