### ISSUE TITLE
Stop metrics collector when app's shutting down

### ISSUE THREAD

**Issue by pintojeremy** [s-r-x/bull-monitor#73]
Hi there,

First of all thanks for your work on Bull-monitor, great piece of software, it makes my life way easier.

I was digging a problem about my app not terminating correctly and found out that an interval was left behind by a package named: `toad-scheduler`.
Turns out Bull-monitor was the one using toad-scheduler.

I couldn't find anything to stop the metrics collector and clean up the scheduler.
Am I missing something?

If you need further information, I'll be glad to answer 😄

**Comment by s-r-x** [comment]
@pintojeremy hi, thank you.

I think this should do the trick:
```typescript
process.on('SIGINT', () => {
  // typescript won't be happy with this one, so you might use ts-ignore or whatever.
  monitor._metricsCollector?.stopCollecting();
});
```

**Comment by s-r-x** [comment]
PRs are highly appreciated. I don't want to make the whole collector public, so i suggest a little facade in the root class for this business (something like "stopMetricsCollector" maybe). wdyt?

**Comment by s-r-x** [comment]
added in **5.4.0**

**Comment by pintojeremy** [comment]
👋 
Sorry it totally slip my mind, business is going hard.
Just noticed the version 5.4.0, thank you very much for your work 👏 .
