### ISSUE TITLE
Support Redis Cluster for BullMQ

### ISSUE THREAD

**Issue by xueya-long** [s-r-x/bull-monitor#76]
Hi, 
We have upgraded the BullMQ in our project recently, and switched to redis cluster. With redis cluster, we get more scalability of our project. As bull-monitor is an important tool for us, it would be very helpful when bull-monitor  also support redis cluster for BullMQ. 

Here is how it works by BullMQ: [Redis cluster](https://docs.bullmq.io/bull/patterns/redis-cluster)

We forked this project and get it running with cluster mode. Basically the change is very easy, nothing need to be changed besides adding some lines into the  [fixtures/bull-server/server/index.ts file](https://github.com/arvatoaws-labs/opswatch-bull-monitor/blob/dev/fixtures/bull-server/server/index.ts)

the connection is a redis cluster, we use ioredis here:
`const bullconnection = new redis.Cluster(bullConf, {
  redisOptions: {
    username: redis_user_bull,
    password: process.env.REDIS_PW_BULL,
    tls: env !== 'local' && env !== 'dev' ? {} : undefined,
  },
  dnsLookup: (address: string, callback: (e: any, a: string) => void) =>
    callback(null, address),
  scaleReads: 'slave',
  enableAutoPipelining: false, //what is this for??
  enableOfflineQueue: true,
  enableReadyCheck: true,
  slotsRefreshTimeout: 500000,
});`

By queue definition, not only the queue name but also the prefixes of the queue is needed:
`for (let i = 0; i < queues.length; i++) {
  mqQueues.push(
    new BullMqQueue(queues[i], {
      prefix: prefixes[i],
      connection: bullconnection,
    })
  );
  queue_prefix_lut.push({
    queue: queues[i],
    prefix: prefixes[i],
  });
}`

To each worker, the prefix also need to be added:
`mqQueues.forEach((queue) => {
  const queuePrefix = queue_prefix_lut.find((i) => i.queue === queue.name);
  new MqWorker(
    queue.name,
    async (job) => {
      return `some return value from ${job.name}`;
    },
    {
      prefix: queuePrefix && queuePrefix.prefix,
      connection: bullconnection,
    }
  );
});`

Redis cluster is a very useful feature of BullMQ, hope you are also interested in it and add it as a feature in bull-monitor. 
here is our [fork repo](https://github.com/arvatoaws-labs/opswatch-bull-monitor)

**Comment by s-r-x** [comment]
@xueya-long I don't quite understand what's going on here. If you want to use  a cluster - just do it, it has nothing to do with bull-monitor. 
Also this  fixture thing that you linked is made only for development purposes.

**Comment by xueya-long** [comment]
Hi @s-r-x ,
bull-monitor is connected with a redis client per REDIS_URI, and this redis client is only for BullMQ caches. The connection for redis client and redis cluster is different. Redis cluster allows us save all caches of the project with big scalability feature. When we chenge the REDIS_URI to cluster uri, bull-monitor cannot connect to the cluster, the connection inside bull-monitor need to be changed. And for redis cluster mode, BullMQ need a hash tag (prefix) for each Queue and Worker.  It is more like a topic for a redis cluster connection for bull-monitor :)

**Comment by s-r-x** [comment]
@xueya-long bull monitor doesn't connect to anything, but your queues are (don't confuse them with bull-monitor adapters).
