### ISSUE TITLE
Better navigation url for queue and job

### ISSUE THREAD

**Issue by weilinzung** [s-r-x/bull-monitor#8]
Looking for a better navigation URL for queue and job, so after refreshing browser that we won't lose the view and we can also easy to share queues or jobs.

![Screen Shot 2021-06-05 at 6 58 12 PM](https://user-images.githubusercontent.com/7368063/120907540-5adb8d80-c630-11eb-8620-d8c5a29b3ee1.png)

**^ Example above that could produce URLs like:** 

- queue URL: https://s-r-x.github.io/bull-monitor/queue-2
- queue type URL: https://s-r-x.github.io/bull-monitor/queue-2?active=true
- job id URL(SEARCH): https://s-r-x.github.io/bull-monitor/queue-2?active=true&search=true&jobId=228750
- job data key URL(search): https://s-r-x.github.io/bull-monitor/queue-2?active=true&search=true&key='key'&term='value-24'

**Also, would be great to add a share button for each job.**

Thanks!!!

**Comment by s-r-x** [comment]
I simplified all that url stuff for purpose, in order to avoid a lot of potential bugs and setup complexity. Current view can be persisted into the local storage, that's a pretty simple one.  What about sharing...  hm, I guess there is no way to do it without query params... But this feature looks valuable and I would like to have that. Let me think about it

**Comment by saade** [comment]
@weilinzung what do you mean by "Share a Job"?

**Comment by weilinzung** [comment]
@saade Mainly I can tell co-workers what job(s) I want to specify. And be able to share multiple jobs while using search filters. 
The easy way I can think is using URL with params, but @s-r-x  already mentioned the current setup without params is for some purposes.

**Comment by s-r-x** [comment]
@weilinzung "so after refreshing browser that we won't lose the view" - this was added in 0.25.0 as workspaces. sharing - in 0.26.0
