### ISSUE TITLE
Problems testing all bull-monitor packages together

### ISSUE THREAD

**Issue by alberto-uelz** [s-r-x/bull-monitor#82]
I have made a fork of your work, since I wanted to add two more options to the bull monitor command "--user" and "--password". I have also added a middleware in express that is able to validate if a HTTP Basic header is sent and if the credentials entered in the command match the header then it lets you through, otherwise it shows unauthorized.

The modifications on the command line client and on the express server are now working and I have been able to validate it.

The problem is that now I have to find a way to communicate those credentials to the front-end application. 

In order to test the code with all the modifications I made in the lerna subpackages, I need to be able to link all the packages in my working directory. I tried to make a "lerna link" but that instruction was removed, I don't know why, the thing is that I had to downgrade lerna version to be able to test the modifications in an effective way.

Can you tell me what version of lerna you use for this package?

Thank you very much

**Comment by s-r-x** [comment]
hi

https://github.com/s-r-x/bull-monitor/blob/main/package.json#L27
